### ISSUE TITLE
初始化和设置值的时候，数组必须转换为整形，这有点蛋疼

### ISSUE THREAD

**Issue by meystack** [hsiangleev/eleTree#10]
最近看了很多tree,觉得作者您的这个挺不错的，
但是经过测试发现

defaultCheckedKeys属性和setChecked方法传入的数组，需要使用parseInt转换成整形，讲真的，这样又得多写三行代码。
。。。。为毛呢？作者在for的时候，直接parseInt不就好了吗？

**Comment by hsiangleev** [comment]
@yavismart 没有说一定要传整形的数据呀，这个根据你的数据格式来的，这个的值要跟你的数据里面的id全等就可以了

**Comment by meystack** [comment]
那明白了。。。。我还以为是有bug. 原来得自己去控制类型

**Comment by hsiangleev** [comment]
@hsiangleev 你用的是哪个版本的，这个是2.0版本的，比较新一点，之前的那个版本的好久没维护了

**Comment by meystack** [comment]
用的2.0版本，树形菜单用的还不错，比原生的要好一点，原生的初始化节点有问题，修复了以后刚好看到eletree就换了这个版本。
另外这个如果对select支持的更好一些就好了，像select下拉树，下拉多选，下拉联动，基本上这个东西就足够用了。
还有目前这个select的下拉 需要自己去实现很多点击，比较麻烦！

**Comment by hsiangleev** [comment]
@yavismart 对的，多谢你的建议，目前这个对下拉树的支持度确实很少，因为看其它的插件有专做下拉树的，这个就没有往这方面深究了，后面可能会增加一些下拉树的支持
