### ISSUE TITLE
eletree2最新版在与layui配合的时候，右键菜单的位置不准。

### ISSUE THREAD

**Issue by 6830920** [hsiangleev/eleTree#13]
启用了rightMenuList ， 右键弹出的菜单不在鼠标点击处，离得很远。

后来检查发现是和layui的css冲突，https://www.layuicdn.com/layui-v2.2.0/css/layui.css

不用这个css，右键菜单的弹出位置就是准的。

**Comment by hsiangleev** [comment]
@6830920 我这边用你说的这个css测试了一下也是正常的，你可以用浏览器控制台查看一下右键菜单的dom  .eleTree-menu上面有没有其它样式影响吗
