### ISSUE TITLE
添加搜索功能时，然后搜索到一个子节点选中该子节点的父节点，会把该父节点下的所有子节点全部选中

### ISSUE THREAD

**Issue by 778663** [hsiangleev/eleTree#16]
搜索到子节点时请问选中当前父节点怎么只选中显示的而不选中隐藏的
![image](https://user-images.githubusercontent.com/53892484/122195110-a27fd600-cec8-11eb-89c6-5defa0d6593c.png)
![image](https://user-images.githubusercontent.com/53892484/122195125-a4499980-cec8-11eb-857b-2444f387ea8c.png)
![image](https://user-images.githubusercontent.com/53892484/122195130-a6135d00-cec8-11eb-8bbb-c1cc4ce139bb.png)

**Comment by hsiangleev** [comment]
@qq1848641981 
* 这种是因为你选中了父节点，默认父子关联的，父节点选中的话，子节点会自动选中的，即使是新添加的子节点也是选中的
* 搜索获取选中的节点有点问题，我给getChecked方法加了第三个参数，即是否包含隐藏节点，默认true包含，传false的话当搜索时只会显示搜索到的选中的节点

**Comment by 778663** [comment]
请问下你改的代码在哪呢😅 @hsiangleev

**Comment by hsiangleev** [comment]
@qq1848641981 等下，还没提交，在改文档。。。

**Comment by 778663** [comment]
好的😅

**Comment by hsiangleev** [comment]
@qq1848641981 提交了已经

**Comment by 778663** [comment]
好的，谢谢🙂

**Comment by 778663** [comment]
@hsiangleev 有1.0版本的吗😅

**Comment by hsiangleev** [comment]
@778663 没有，1.0版本的代码jquery写的有点乱，已经维护不下去了，所以才重新写的一个。。。

**Comment by 778663** [comment]
好吧😅
