### ISSUE TITLE
checkbox Bug提交

### ISSUE THREAD

**Issue by AspireLove** [hsiangleev/eleTree#17]
初始化数据checkbox为禁用状态，当使用updateKeySelf方法更新后（将checkbox改为启用），选择子节点时父节点没有默认选中。

**Comment by hsiangleev** [comment]
@AspireLove 我这边测试的可以呀，你看一下这个示例[https://codepen.io/hsiangleev/pen/xxqBgxQ](https://codepen.io/hsiangleev/pen/xxqBgxQ)

**Comment by AspireLove** [comment]
从左到右以此启用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsiangleev/eleTree"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hsiangleev/eleTree] checkbox Bug提交 (#17)





 
@AspireLove 我这边测试的可以呀，你看一下这个示例https://codepen.io/hsiangleev/pen/xxqBgxQ

**Comment by AspireLove** [comment]
邮箱发送了一个示例，麻烦看一下

**Comment by hsiangleev** [comment]
@ @AspireLove 没有看到示例呀

**Comment by AspireLove** [comment]
@hsiangleev 附件

**Comment by hsiangleev** [comment]
@AspireLove 我找半天也没找到你在哪发的附件。。。

**Comment by AspireLove** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>eleTree</title>
  <link rel="stylesheet" href="//unpkg.com/eletree/dist/css/icon.css"  type="text/css">
</head>
<body>
  <button id="a1">启用节点</button>
  <button id="a2">启用节点</button>
  <button id="a3">启用节点</button>
  <button id="a4">启用节点</button>
	<div class="eletree"></div>
	<script src="//unpkg.com/eletree/dist/eleTree.js"></script>
</body>
</html>
<script>
var data = [
  {
    "label": "安徽省",
    "id": "001",
    "isOpen": true,
    "disabled": true,
    "children": [
      {
        "label": "淮北市",
        "disabled": true,
        "id": "001001"
      },
      {
        "label": "马鞍山市",
        "id": "001002",
        "disabled": true,
        "isOpen": true,
        "children": [
          {
            "label": "花山区",
            "id": "001002001",
            "disabled": true,
            "isOpen": true,
            "children": [
              {
                "label": "霍里街道",
                "checked": false,
                "disabled": true,
                "id": "001002002001"
              },
              {
                "label": "桃源路",
                "disabled": true,
                "id": "001002002002"
              },
              {
                "label": "湖东路",
                "checked": false,
                "disabled": true,
                "id": "001002002003"
              }
            ]
          },
          {
            "label": "雨山区",
            "disabled": true,
            "id": "001002002"
          },
          {
            "label": "和县",
            "disabled": true,
            "id": "001002003"
          }
        ]
      },
      {
        "label": "合肥市",
        "disabled": true,
        "id": "001003"
      }
    ]
  }
]

var ele = eleTree({
  el: '.eletree',
  data: data,
  showCheckbox: true,
  highlightCurrent: true,
  showRadio: true,
  imgUrl: "//unpkg.com/eletree/dist/images/",
  icon: {
    fold: "fold.png",
    leaf: "leaf.png",
    checkFull: ".eletree_icon-check_full",
    checkHalf: ".eletree_icon-check_half",
    checkNone: ".eletree_icon-check_none",
    dropdownOff: ".eletree_icon-dropdown_right",
    dropdownOn: ".eletree_icon-dropdown_bottom",
    loading: ".eleTree-animate-rotate.eletree_icon-loading1",
    radioCheck: "radioCheck.png",
    radioCheckNone: "radioCheckNone.png",
  }
})
document.getElementById("a1").onclick=function() {
  ele.updateKeySelf('001',{
    disabled: false
  })
}
document.getElementById("a2").onclick=function() {
  ele.updateKeySelf('001002',{
    disabled: false
  })
}
document.getElementById("a3").onclick=function() {
  ele.updateKeySelf('001002001',{
    disabled: false
  })
}
document.getElementById("a4").onclick=function() {
  ele.updateKeySelf('001002002001',{
    disabled: false
  })
}
</script>

**Comment by AspireLove** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>eleTree</title>
  <link rel="stylesheet" href="//unpkg.com/eletree/dist/css/icon.css"  type="text/css">
</head>
<body>
  <button id="a1">启用节点</button>
  <button id="a2">启用节点</button>
  <button id="a3">启用节点</button>
  <button id="a4">启用节点</button>
	<div class="eletree"></div>
	<script src="//unpkg.com/eletree/dist/eleTree.js"></script>
</body>
</html>

**Comment by AspireLove** [comment]
@hsiangleev 这个上面发不全

**Comment by AspireLove** [comment]
> <!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>eleTree</title>
  <link rel="stylesheet" href="//unpkg.com/eletree/dist/css/icon.css"  type="text/css">
</head>
<body>
  <button id="a1">启用节点</button>
  <button id="a2">启用节点</button>
  <button id="a3">启用节点</button>
  <button id="a4">启用节点</button>
	<div class="eletree"></div>
	<script src="//unpkg.com/eletree/dist/eleTree.js"></script>
</body>
</html>

**Comment by hsiangleev** [comment]
@AspireLove 那你发一个全的呀，这个评论不是可以用markdown格式吗，你把代码用这个包一下  **```**

**Comment by AspireLove** [comment]
```
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>eleTree</title>
  <link rel="stylesheet" href="//unpkg.com/eletree/dist/css/icon.css"  type="text/css">
</head>
<body>
  <button id="a1">启用节点</button>
  <button id="a2">启用节点</button>
  <button  #id="a3">启用节点</button>
  <button id="a4">启用节点</button>
	<div class="eletree"></div>
	<script src="//unpkg.com/eletree/dist/eleTree.js"></script>
</body>
</html>
```

**Comment by AspireLove** [comment]
```
<script>
var data = [
  {
    "label": "安徽省",
    "id": "001",
    "isOpen": true,
    "disabled": true,
    "children": [
      {
        "label": "淮北市",
        "disabled": true,
        "id": "001001"
      },
      {
        "label": "马鞍山市",
        "id": "001002",
        "disabled": true,
        "isOpen": true,
        "children": [
          {
            "label": "花山区",
            "id": "001002001",
            "disabled": true,
            "isOpen": true,
            "children": [
              {
                "label": "霍里街道",
                "checked": false,
                "disabled": true,
                "id": "001002002001"
              },
              {
                "label": "桃源路",
                "disabled": true,
                "id": "001002002002"
              },
              {
                "label": "湖东路",
                "checked": false,
                "disabled": true,
                "id": "001002002003"
              }
            ]
          },
          {
            "label": "雨山区",
            "disabled": true,
            "id": "001002002"
          },
          {
            "label": "和县",
            "disabled": true,
            "id": "001002003"
          }
        ]
      },
      {
        "label": "合肥市",
        "disabled": true,
        "id": "001003"
      }
    ]
  }
]

var ele = eleTree({
  el: '.eletree',
  data: data,
  showCheckbox: true,
  highlightCurrent: true,
  showRadio: true,
  imgUrl: "//unpkg.com/eletree/dist/images/",
  icon: {
    fold: "fold.png",
    leaf: "leaf.png",
    checkFull: ".eletree_icon-check_full",
    checkHalf: ".eletree_icon-check_half",
    checkNone: ".eletree_icon-check_none",
    dropdownOff: ".eletree_icon-dropdown_right",
    dropdownOn: ".eletree_icon-dropdown_bottom",
    loading: ".eleTree-animate-rotate.eletree_icon-loading1",
    radioCheck: "radioCheck.png",
    radioCheckNone: "radioCheckNone.png",
  }
})
document.getElementById("a1").onclick=function() {
  ele.updateKeySelf('001',{
    disabled: false
  })
}
document.getElementById("a2").onclick=function() {
  ele.updateKeySelf('001002',{
    disabled: false
  })
}
document.getElementById("a3").onclick=function() {
  ele.updateKeySelf('001002001',{
    disabled: false
  })
}
document.getElementById("a4").onclick=function() {
  ele.updateKeySelf('001002002001',{
    disabled: false
  })
}
</script>

```

**Comment by hsiangleev** [comment]
@AspireLove 确实有点问题，有一个状态没有置回来，已经修复了，感谢反馈
