### ISSUE TITLE
右键菜单的小问题

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [hsiangleev/eleTree#18]
1. 点击编辑后,鼠标无法点击选中文字的位置开始编辑,只能通过键盘左右键来移动光标.
2. 添加同级或下级菜单,在编辑完成后,无法通过回车触发提交事件.需要手动将鼠标点击其他地方才触发.

希望可以改进这2个功能,好像做反了的样子,编辑时需要鼠标有效,添加时需要回车可以添加

**Comment by hsiangleev** [comment]
@974988176 
1. 编辑的时候可以选择位置呀![https://images.hsianglee.cn//img/2021/06/24/20210624174913.png](https://images.hsianglee.cn//img/2021/06/24/20210624174913.png)，点击input里面不是可以选吗
2. 回车保存功能明天有时间的话可以加一下

**Comment by Mr-ShiHuaYu** [comment]
@hsiangleev 
可是我这里不知道为什么,选择编辑后,点击input框的任何位置,都没有反应,只能通过键盘的左右

**Comment by hsiangleev** [comment]
@974988176 你用你的配置在这个上面测试一下[https://codepen.io/hsiangleev/pen/vYxWPKg](https://codepen.io/hsiangleev/pen/vYxWPKg)，如果还是有问题的话，你把你的eletree配置发给我，我试试

**Comment by 974988176** [comment]
@hsiangleev 在这上面是可以的

`
var ele = eleTree({
  el: '.eletree',
  data: data,
  highlightCurrent: true,
  rightMenuList: ["copy", "paste", "paste_before", "paste_after", "cut_paste", "edit", "remove", "add_child", "add_before", "add_after"],
  rightMenuList: [
    {name:"编辑", value: "edit"},
    {name:"删除", value: "remove"},
    {name:"添加下级", value: "add_child"},
    {name:"添加同级", value: "add_after"},
  ]
})
`

**Comment by Mr-ShiHuaYu** [comment]
@hsiangleev 
在这上面是可以的,但我用的是layui,不知道是不是跟z-index有关
`
var ele = eleTree({
  el: '.eletree',
  data: data,
  indent: 30,
  request: {
    name: "name",
    key: "id",
    children: "child",
    pid: "pid",
    isOpen: "open",
    checked: "checked"
  },
  highlightCurrent: true,
  rightMenuList: [
    {name:"编辑", value: "edit"},
    {name:"删除", value: "remove"},
    {name:"添加下级", value: "add_child"},
    {name:"添加同级", value: "add_after"},
  ]
})
`

**Comment by hsiangleev** [comment]
@974988176 
1. 按entry键保存功能已经加上了
2. 这个鼠标不能点击的问题因为我这边也看不到效果，不知道是不是我这边的问题，所以没有处理

**Comment by Mr-ShiHuaYu** [comment]
@hsiangleev 好的,非常感谢,楼主辛苦了,有可能是因为我是在iframe里面使用的,我点击Input框的时候,开发者里面就看到"eleTree-title eleTree-title-active"这个div的class在闪,没有其他反应,但点击同一行,不是Input框 ,可以取消编辑.谢谢.可能说一下这个编辑功能在哪个文件吗?我尝试着自己改一下

**Comment by hsiangleev** [comment]
@974988176 编辑功能在3个文件下面，`/src/event/textEditBlur.js`, `/src/methods/edit.js`, `/src/vnode/textVnode.js`
