### ISSUE TITLE
当数据只有一条时，显示异常

### ISSUE THREAD

**Issue by EddieChen97** [hsiangleev/eleTree#19]
如题，当只有一条数据时，树为空

**Comment by hsiangleev** [comment]
@EddieChen97 我这边测试了一下，没有出现这个问题
![](https://images.hsianglee.cn//img/2021/07/13/20210713084735.png)

**Comment by EddieChen97** [comment]
@hsiangleev 我使用的是pid方式渲染
> 接口数据

![image](https://user-images.githubusercontent.com/46082489/125373844-6866fe80-e3b8-11eb-8373-6a0167887d51.png)
> 显示效果：

![image](https://user-images.githubusercontent.com/46082489/125373910-80d71900-e3b8-11eb-8c59-6d3f352c908d.png)


> @EddieChen97 我这边测试了一下，没有出现这个问题
> ![](https://camo.githubusercontent.com/cb9f2e9ebb140d6b91a085064a01fc66a75383f88fff7cb50689e3135f58bc06/68747470733a2f2f696d616765732e687369616e676c65652e636e2f2f696d672f323032312f30372f31332f32303231303731333038343733352e706e67)

**Comment by hsiangleev** [comment]
@EddieChen97 有一个defaultPid属性，意思是当使用pid格式的数据时第一层数据的默认值，默认是空，因为你这边pid第一层用的是0，所以加一个参数，defaultPid:0，就可以了
