### ISSUE TITLE
可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样

### ISSUE THREAD

**Issue by ay2034456** [hsiangleev/eleTree#2]
![image](https://user-images.githubusercontent.com/31758203/90720751-c34bbf00-e2e9-11ea-8542-26142d7713e5.png)

**Comment by hsiangleev** [comment]
@ay2034456 感谢你的意见，功能已添加

**Comment by ay2034456** [comment]
棒棒的

**Comment by ay2034456** [comment]
大佬，有木有好用的表格树啊，可以固定表头、固定列、合计、合并列等，推荐下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李祥"<notifications@github.com&gt;; 
发送时间: 2020年8月22日(星期六) 下午2:29
收件人: "hsiangleev/eleTree"<eleTree@noreply.github.com&gt;; 
抄送: "心随YOU"<592085147@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2)





 
@ay2034456 感谢你的意见，功能已添加

**Comment by hsiangleev** [comment]
@ay2034456 我也没怎么用过这种。。。

**Comment by fengyts** [comment]
> 大佬，有木有好用的表格树啊，可以固定表头、固定列、合计、合并列等，推荐下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "李祥"<notifications@github.com&gt;; 发送时间: 2020年8月22日(星期六) 下午2:29 收件人: "hsiangleev/eleTree"<eleTree@noreply.github.com&gt;; 抄送: "心随YOU"<592085147@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2) @ay2034456 感谢你的意见，功能已添加 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你说的表格，可以用layui的动态表格，layui很强大的

**Comment by ay2034456** [comment]
谢谢啊，layui我用过，其中还是有不满足的，我再网上叶找了一个layui拓展&nbsp; treeTable的插件（https://blog.csdn.net/zyg1515330502/article/details/94554820），满足一些，但是作者好久不更新了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsiangleev/eleTree"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 晚上9:25
收件人:&nbsp;"hsiangleev/eleTree"<eleTree@noreply.github.com&gt;;
抄送:&nbsp;"心随YOU"<592085147@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2)





  
大佬，有木有好用的表格树啊，可以固定表头、固定列、合计、合并列等，推荐下
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "李祥"<notifications@github.com&gt;; 发送时间: 2020年8月22日(星期六) 下午2:29 收件人: "hsiangleev/eleTree"<eleTree@noreply.github.com&gt;; 抄送: "心随YOU"<592085147@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2) @ay2034456 感谢你的意见，功能已添加 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你说的表格，可以用layui的动态表格，layui很强大的

**Comment by ay2034456** [comment]
大佬，再搜索的时候，比如我有三层节点，我搜索二级节点名称的时候，可以手动点击展开三级节点吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsiangleev/eleTree"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月22日(星期六) 下午2:29
收件人:&nbsp;"hsiangleev/eleTree"<eleTree@noreply.github.com&gt;;
抄送:&nbsp;"心随YOU"<592085147@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2)





 
@ay2034456 感谢你的意见，功能已添加

**Comment by hsiangleev** [comment]
@ay2034456 搜索如果只搜索到二级节点的话，三级节点没搜索到不是就已经隐藏了吗，那展不展开又有什么关系呢

**Comment by ay2034456** [comment]
因为是想选择三级节点的数据，但是只记得一二级节点的名称，不记得三级节点的名称的时候，搜索二级节点就能展示二级节点的数据，然后点击二级节点在展示三级节点的数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsiangleev/eleTree"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 中午1:44
收件人:&nbsp;"hsiangleev/eleTree"<eleTree@noreply.github.com&gt;;
抄送:&nbsp;"心随YOU"<592085147@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2)





 
@ay2034456 搜索如果只搜索到二级节点的话，三级节点没搜索到不是就已经隐藏了吗，那展不展开又有什么关系呢

**Comment by hsiangleev** [comment]
@ay2034456 这种感觉不是太好吧，如果只搜索到二级的节点，然后一共有五六级的话，总不能子节点没有搜索到也全部显示并且全部展开吧

**Comment by ay2034456** [comment]
不是直接展开，比如：公司=》部门=》人员，我搜索部门名称（一二级节点展开），然后点击部门名称前面的“+”或者“&gt;”符号的时候，在展开下级节点（人员）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsiangleev/eleTree"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 中午1:59
收件人:&nbsp;"hsiangleev/eleTree"<eleTree@noreply.github.com&gt;;
抄送:&nbsp;"心随YOU"<592085147@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2)





 
@ay2034456 这种感觉不是太好吧，如果只搜索到二级的节点，然后一共有五六级的话，总不能子节点没有搜索到也全部显示并且全部展开吧

**Comment by hsiangleev** [comment]
@ay2034456 
1. 我看了一下，elementUI的tree和ztree的搜索，应该都没有搜索父节点，还去显示子节点的，[ztree](http://www.treejs.cn/v3/demo.php#_516)
2. 那如果你说的  公司=》部门=》人员，如果一开始就是展开的，那搜索到部门的话，还要展示人员那一级吗？如果展示的话，不就误以为搜索到的是人员那一级了吗
3. 我感觉既然是搜索的话，应该最后一级就是搜索到的节点。。。

**Comment by ay2034456** [comment]
ztree的这种效果，ztree官网没有，拓展出来的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsiangleev/eleTree"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 下午2:15
收件人:&nbsp;"hsiangleev/eleTree"<eleTree@noreply.github.com&gt;;
抄送:&nbsp;"心随YOU"<592085147@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hsiangleev/eleTree] 可以在搜索的时候直接，把搜索的内容展开吗？就像下图一样 (#2)





 
@ay2034456
  
我看了一下，elementUI的tree和ztree的搜索，应该都没有搜索父节点，还去显示子节点的，ztree
 
那如果你说的  公司=》部门=》人员，如果一开始就是展开的，那搜索到部门的话，还要展示人员那一级吗？如果展示的话，不就误以为搜索到的是人员那一级了吗
 
我感觉既然是搜索的话，应该最后一级就是搜索到的节点。。。
