### ISSUE TITLE
嵌在layUI选项卡中，右键菜单头几个会飘很远

### ISSUE THREAD

**Issue by ALuShu** [hsiangleev/eleTree#21]
详情：
1、layui的tab选项卡中，加入layui的卡片面板布局，再写入eletree，开头好多个会飘得很远，如图：
![image](https://user-images.githubusercontent.com/49304693/130398924-808e6419-6036-4581-91b2-2fbd6a9840ac.png)

拖到下面的一些选项则不会，如图：
![image](https://user-images.githubusercontent.com/49304693/130399345-d92af47b-5787-4501-8f7a-7c8c013c2e39.png)

似乎开头的几个的top都会多出100px左右，不知什么原因

**Comment by hsiangleev** [comment]
已修改
