### ISSUE TITLE
updateKeySelf函数无法删除属性

### ISSUE THREAD

**Issue by ALuShu** [hsiangleev/eleTree#22]
如题，使用
`ele.updateKeySelf(data.data.id, data.data)`
可以新增、更新一些自定义的属性，用于后台处理，但是`delete data.data.属性`之后去`updateKeySelf()`，自定义属性依然存在，没有删除

**Comment by hsiangleev** [comment]
@ALuShu 因为updateKeySelf方法修改的变量可以只传部分属性，所以不传该属性，不代表就是删除该属性，updateKeySelf属性不支持删除属性
