### ISSUE TITLE
isOpen属性渲染后变成int类型

### ISSUE THREAD

**Issue by ALuShu** [hsiangleev/eleTree#23]
后台接口返回的数据是children格式的，如下：
![image](https://user-images.githubusercontent.com/49304693/131435286-06370c8c-a00e-4811-9db3-052298a547c8.png)
boolean类型的数据都是正常的，经过下面的处理渲染：
`
/**
	 * 目录树数据
	 */
	var treeData = [];
	/**
	 * 完整数据
	 *
	 * @type {*[]}
	 */
	var fullData = [];
$.ajax({
			url : '../content.do',
			type:'POST',
			dataType: 'json',
			async: false,
			success : function(data) {
				if (!data['success']) {
					layer.msg(data['msg'], {icon: 2,time: 5000});
				}
				fullData = data.obj;
				if (fullData !== null) {
					for (let item of fullData) {
						if (item['eleTree'] !== null) {
							treeData.push(item['eleTree'])
						}
					}
				}
			}
		});

// eleTree实例化
		var ele = eleTree({
			el: '#eletree1',
			data: treeData,
			draggable: true,
			indent: 30,
			highlightCurrent: true,
			accordion: true,
			imgUrl: "../../plugins/eletree/images/",
			icon: {
				fold: "connections.png",
				leaf: "video.png",
				checkFull: ".eletree_icon-check_full",
				checkHalf: ".eletree_icon-check_half",
				checkNone: ".eletree_icon-check_none",
				dropdownOff: ".eletree_icon-dropdown_right",
				dropdownOn: ".eletree_icon-dropdown_bottom",
				loading: ".eleTree-animate-rotate.eletree_icon-loading1",
				radioCheck: "radioCheck.png",
				radioCheckNone: "radioCheckNone.png",
			},
			customText: function(data) {
				var s = data.label
				if (data.pid === "") {
					s+=`<i class="eletree_icon-edit edit_test"></i>
                	<i class="eletree_icon-delete delete_test"></i>`
				}
				return s
			}
		})
`
这是渲染后log出来的数据，上面是on事件的data，下面是我上面ajax存起来的一个treeData，事件的data.data正常，不知为啥treeData会在渲染后改变这个值，true为2，false为0
![image](https://user-images.githubusercontent.com/49304693/131435946-677f6f01-401f-482a-9943-979ad9e0fc0e.png)

**Comment by hsiangleev** [comment]
@ALuShu 
1. 这个数据是我在内部转的，因为有三种状态，布尔值表示不了了，所以我用012分别代替一种状态
2. 这个数据可以不用管，如果需要这个数据，可以用getAllNodeData方法获取所有的数据，然后给treeData重新赋值

**Comment by ALuShu** [comment]
@hsiangleev 好的，已经用别的方案解决
