### ISSUE TITLE
树的 ico 图标自定义

### ISSUE THREAD

**Issue by 156704883** [hsiangleev/eleTree#27]
是否可以支持多类型图标节点的自定义，比如 有 设备图标、组织图标、人员图标 等，现在只有目录和节点两种类型, ico 的自体图标最好能支持 color 的属性，这样就可以改颜色，不然就是黑白的

**Comment by hsiangleev** [comment]
@156704883 谢谢你的建议，最近在忙其它的事，后面看情况可以添加一下

**Comment by hsiangleev** [comment]
已添加
