### ISSUE TITLE
sort field 非 label 字段无效果

### ISSUE THREAD

**Issue by 156704883** [hsiangleev/eleTree#29]
var organization_data = [
					{id:1000,label:'根组织',type:0,sort_:1,children:[
							{id:1001,label:'江苏省',type:0,icon:'chf-icon chf-icon-zuzhijiagou',sort_:1,
								children:[
									{id:1002,label:'南通市',type:0,icon:'chf-icon chf-icon-zuzhijiagou',sort_:1},
									{id:1003,label:'南京市',type:2,icon:'chf-icon chf-icon-zuzhijiagou',sort_:0}
									]
							},
							{id:2001,label:'安回省',type:0,icon:'chf-icon chf-icon-zuzhijiagou',sort_:0,
								children:[
									{id:2002,label:'a市',type:0,icon:'chf-icon chf-icon-zuzhijiagou',sort_:0},
									{id:2003,label:'b市',type:2,icon:'chf-icon chf-icon-zuzhijiagou',sort_:1}
								]
							}
						]},
					{id:3000,label:'根组织3',type:0,sort_:0}
				];

el5.sort({
					field: "sort_",   /*这里用 sort_无效果，换成 label 有效果*/
					type: "desc",
				})

看源码 sort.js 是有用到 field 的，不知道问题出在哪儿

**Comment by zheng-qiang0313** [comment]
`  "asc" === u ? t.sort((function (e, t) {
                    return "number" == typeof e[a] ? e[a] - t[a] : e[a].localeCompare(t[a])
                })) : "desc" === u && t.sort((function (e, t) {
                    return "number" == typeof e[a] ? t[a] - e[a] : t[a].localeCompare(e[a])
                }))`
 return "number" == typeof e[a] ? e - t: e[a].localeCompare(t[a]);
e - t少了参数

**Comment by hsiangleev** [comment]
已修改
