### ISSUE TITLE
怎么全选和反选所有的节点数据

### ISSUE THREAD

**Issue by fengyts** [hsiangleev/eleTree#3]
1. 怎么设置一个按钮用来 一键全选和反选 所有的节点数据，比如你的例子中省市的数据，有33个省市平级的，我怎么去全选和反选啊。
2.
![image](https://user-images.githubusercontent.com/15372856/92483001-db449d80-f21a-11ea-81bb-276003db28e7.png)
我的这个左边的线条看着好粗啊，不像官网显示的那么纤细，不知市何原因。
3. 看你官网做的这么全，想提点个人意见，不喜可略过。
不知是否用过 zTree 插件，这个是我用过的迄今为止最好用、文档最全的树插件，作者可以去参考下。
别人有的功能你要有，别人没有的你更要有，这样才能有竞争力。
哈哈，纯属个人意见，不喜勿喷。

**Comment by hsiangleev** [comment]
@fengyts 非常感谢你的意见
1. 全选和反选可以加一个，之前没有想到这个。。
2. 这个线条看着像1.0之前的版本，你用的是哪个，js文件最上面有版本号，1.0后面的版本和2.0的应该线条都是纤细的
3. ztree的文档也看过一点，部分功能也有借鉴
