### ISSUE TITLE
请问如何通过传入ID选中高亮节点并展开相应的所有父级

### ISSUE THREAD

**Issue by xjindf** [hsiangleev/eleTree#35]
你好，我需要通过ID查找并选中指定节点，请问如何实现

**Comment by hsiangleev** [comment]
@xjindf 
- 不好意思，之前在忙其他事情
- 我添加了三个方法[https://eletree.hsianglee.cn/eleTree/update-log.html#_2-3-2](https://eletree.hsianglee.cn/eleTree/update-log.html#_2-3-2)
- [具体说明](https://eletree.hsianglee.cn/eleTree/usedocs-methods.html)最下面的三个方法
- [使用示例](https://eletree.hsianglee.cn/eleTree/demo-methods.html)

**Comment by xjindf** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月21日(星期一) 下午2:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hsiangleev/eleTree] 请问如何通过传入ID选中高亮节点并展开相应的所有父级 (Issue #35)





 
@xjindf
  
不好意思，之前在忙其他事情
 
我添加了三个方法https://eletree.hsianglee.cn/eleTree/update-log.html#_2-3-2
 
具体说明最下面的三个方法
 
使用示例
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
