### ISSUE TITLE
接口有返回数据打印的时候data为空

### ISSUE THREAD

**Issue by Wang20190217** [hsiangleev/eleTree#41]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/55485415/178808915-42fb3349-5545-4bca-892b-69bb007bf7ce.png">
<img width="694" alt="屏幕截图 2022-07-14 025259" src="https://user-images.githubusercontent.com/55485415/178810015-c8cfff98-d19f-4bfa-9525-87ebb47e38d4.png">
<img width="712" alt="屏幕截图 2022-07-14 025319" src="https://user-images.githubusercontent.com/55485415/178810021-fab21256-efe5-4c04-9380-a2600ed6613d.png">

**Comment by Wang20190217** [comment]
大佬指定迷津，捣鼓不出来。

**Comment by hsiangleev** [comment]
@Wang20190217 我这边测试了一下，没有重现这个问题，你用第一个url有没有问题呢 
![20220714103440.png](https://images.hsianglee.cn/pwsh_img/20220714103440.png)

**Comment by Wang20190217** [comment]
第一个第二个路径都可以，就是第三个异步调用会有这个情况。按道理来说接口中其他两个字段都又数据，data数组是空的我很不理解，其他路径有值。难道是我返回的数据格式问题吗
![image](https://user-images.githubusercontent.com/55485415/178897205-a886def2-8551-46bc-8e1f-c15e01c06514.png)
![image](https://user-images.githubusercontent.com/55485415/178897253-b992d5b1-c30f-46da-82e0-f147787899c4.png)

**Comment by hsiangleev** [comment]
@Wang20190217 你的第一层pid的值不对，默认是""，或者修改配置参数`defaultPid: "0"`

**Comment by Wang20190217** [comment]
感谢，问题解决了。辛苦
