### ISSUE TITLE
CDN引入脚本时，2次加载报错

### ISSUE THREAD

**Issue by panpu** [hsiangleev/eleTree#5]
我在页面使用CDN加载的方式引入该插件，通过路由切换切换时，2次加载带有该插件的页面时会报错，提示：only one instance of babel-polyfill is allowed，该问题是什么原因引起的，该如何解决或避免呢？

**Comment by hsiangleev** [comment]
@panpu 应该是插件在同一个页面加载两次的问题，所以你先别在切换路由的时候加载，在外层框架上引入这个插件试一下看看
