### ISSUE TITLE
异步渲染报错

### ISSUE THREAD

**Issue by ztb982** [hsiangleev/eleTree#6]
eletree V2.2.11 版本 
使用异步加载树结构时 ,  会报 uncaught in promise 错误  这个是不是插件 .catch()没有加上去的问题呢

**Comment by hsiangleev** [comment]
@ztb982 我这边测试没有发现问题，可以详细说一下怎么能重现错误吗，还有你那边用的是什么浏览器

**Comment by ztb982** [comment]
google v86.0.4240.75





接口请求成功了&nbsp; 感觉是数据渲染的时候出了问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李祥"<notifications@github.com&gt;; 
发送时间: 2020年11月28日(星期六) 中午11:05
收件人: "hsiangleev/eleTree"<eleTree@noreply.github.com&gt;; 
抄送: "钟天保"<874291064@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hsiangleev/eleTree] 异步渲染报错 (#6)





 
@ztb982 我这边测试没有发现问题，可以详细说一下怎么能重现错误吗，还有你那边用的是什么浏览器
