### ISSUE TITLE
使用cdn或者layui方式时报错Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by cuiliang0302** [hsiangleev/eleTree#7]
如题所示，使用cdn或者layui方式时，均提示Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

这是我的html代码，粘贴说明文档
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>笔记目录编排</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="//eletreejs.surge.sh/eleTree.js"></script>
    
    <link rel="stylesheet" href="//eletreejs.surge.sh/css/icon.css">
</head>
<body>
<script>
    var data = [
        {
            "label": "安徽省",
            "id": "001",
            "isOpen": true,
            "children": [
                {
                    "label": "淮北市",
                    "id": "001001"
                },
                {
                    "label": "马鞍山市",
                    "id": "001002",
                    "isOpen": true,
                    "children": [
                        {
                            "label": "花山区",
                            "id": "001002001",
                            "isOpen": true,
                            "children": [
                                {
                                    "label": "霍里街道",
                                    "disabled": true,
                                    "checked": true,
                                    "id": "001002002001",
                                    "radioDisabled": true
                                },
                                {
                                    "label": "桃源路",
                                    "id": "001002002002"
                                },
                                {
                                    "label": "湖东路",
                                    "checked": true,
                                    "id": "001002002003",
                                    "radioChecked": true
                                }
                            ]
                        },
                        {
                            "label": "雨山区",
                            "id": "001002002"
                        },
                        {
                            "label": "和县",
                            "id": "001002003"
                        }
                    ]
                },
                {
                    "label": "合肥市",
                    "id": "001003"
                }
            ]
        },
        {
            "label": "河南省",
            "id": "002",
            "children": [
                {
                    "label": "郑州市",
                    "id": "002001"
                },
                {
                    "label": "开封市",
                    "id": "002002"
                }
            ]
        },
        {
            "label": "江苏省",
            "id": "003",
            "children": [
                {
                    "label": "苏州市",
                    "id": "003001"
                },
                {
                    "label": "南京市",
                    "id": "003002"
                },
                {
                    "label": "无锡市",
                    "id": "003003"
                },
                {
                    "label": "徐州市",
                    "id": "003004"
                }
            ]
        }
    ]

    var ele = eleTree({
        el: '.eletree',
        data: data,
        showCheckbox: true,
        highlightCurrent: true,
        showRadio: true,
        imgUrl: "//eletreejs.surge.sh/images/",
        icon: {
            fold: "fold.png",
            leaf: "leaf.png",
            checkFull: ".eletree_icon-check_full",
            checkHalf: ".eletree_icon-check_half",
            checkNone: ".eletree_icon-check_none",
            dropdownOff: ".eletree_icon-dropdown_right",
            dropdownOn: ".eletree_icon-dropdown_bottom",
            loading: ".eleTree-animate-rotate.eletree_icon-loading1",
            radioCheck: "radioCheck.png",
            radioCheckNone: "radioCheckNone.png",
        }
    })
    ele.on('checkbox', function (data) {
        // console.log(this)
        console.log(data)
    })
    ele.on('radio', function (data) {
        // console.log(this)
        console.log(data)
    })
    //监听提交
    form.on('submit(demo1)', function (data) {
        layer.alert(JSON.stringify(data.field), {
            title: '最终的提交信息'
        })
        return false;
    })
</script>

</body>
</html>

**Comment by hsiangleev** [comment]
@cuiliang0302 应该缺少dom元素吧，你页面上面写`<div class="eletree"></div>`了吗

**Comment by cuiliang0302** [comment]
是的，页面忘记加dom元素了


在 2020年12月5日 09:26，李祥<notifications@github.com> 写道：


@cuiliang0302 应该缺少dom元素吧，你页面上面写<div class="eletree"></div>了吗
