### ISSUE TITLE
setChecked选中

### ISSUE THREAD

**Issue by Miss-Jl** [hsiangleev/eleTree#8]
setChecked只能选中数据的第一层吗？子节点怎么设置不了选中？

**Comment by hsiangleev** [comment]
@Miss-Jl 我测试的可以啊，官网上面的方法示例里面有这个示例，你可以试一下，看看跟你的哪里不一样

**Comment by Miss-Jl** [comment]
**如果数据是闭和状态，而非展开状态的情况下**
设置选中，子节点是选不中的；还请看一下

**Comment by hsiangleev** [comment]
@Miss-Jl 测试的就是闭合的，你试一下这个示例看看跟你的有什么不一样[https://codesandbox.io/s/snowy-violet-f7dn1?file=/index.html](https://codesandbox.io/s/snowy-violet-f7dn1?file=/index.html)
